# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-10 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitheart', '0010_articles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='content',
        ),
        migrations.AddField(
            model_name='articles',
            name='content_shortcut',
            field=models.TextField(default='', max_length=300),
        ),
    ]
