# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-10 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitheart', '0011_auto_20170110_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='img_icon',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
