# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-10 03:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitheart', '0016_articles_date_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='date_created',
        ),
    ]
