# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-10 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitheart', '0019_auto_20170110_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
