# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-11 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('img_icon', models.ImageField(upload_to='')),
                ('img', models.ImageField(upload_to='')),
                ('content_shortcut', models.TextField(default='', max_length=200)),
                ('content', models.TextField(default='', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('model', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('url', models.CharField(default='', max_length=100)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitheart.ProductGroup'),
        ),
        migrations.AddField(
            model_name='articles',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitheart.Product'),
        ),
    ]
