# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-10 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitheart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='product',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='fitheart.Product'),
            preserve_default=False,
        ),
    ]
