# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-09 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitheart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
