# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-10 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitheart', '0002_articles_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='articles',
            name='content_shortcut',
            field=models.TextField(default='', max_length=200),
        ),
    ]
