# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-10 14:44
from __future__ import unicode_literals

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fitheart', '0003_auto_20170110_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
