# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-09 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitheart', '0004_remove_product_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
