# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-09 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitheart', '0006_remove_productgroup_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='products',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='fitheart.Product'),
            preserve_default=False,
        ),
    ]
