# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-09 10:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitheart', '0008_auto_20170109_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
