# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-09 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitheart', '0009_productgroup_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=100)),
                ('date_created', models.DateTimeField()),
                ('content', models.TextField(default='', max_length=2000)),
            ],
        ),
    ]
