# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-10 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitheart', '0013_remove_articles_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content_shortcut',
            field=models.TextField(default='', max_length=100),
        ),
    ]
