# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-10 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitheart', '0014_auto_20170110_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='content',
            field=models.TextField(default='', max_length=800),
        ),
    ]
