# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-01-10 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitheart', '0015_articles_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='date_created',
            field=models.DateTimeField(default=2),
            preserve_default=False,
        ),
    ]
